import asyncio
import base64
import json
import os
import pandas as pd
import io
from openai import AsyncOpenAI
from typing import List, Dict, Any
from datapipeline.caption_generation.hintfactory import HintFactory
from google import genai
from google.genai import types
# ==========================================
# 1. 配置与定义
# ==========================================

# 请替换为你的 API Key
API_KEY = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
MODEL_NAME = "ep-20251028151816-lv47m"  # 必须使用支持 Vision 的模型
CONCURRENCY_LIMIT = 128  # 同时并发请求的数量 (根据你的 Tier 调整)

# 你的分类体系 (这里只截取部分作为示例，实际运行时请放入完整 CSV)，实际过程中只根据三级标签生产hint
TAXONOMY_CSV = """
名词细项
Micro-LED display
微型LED显示 (MicroLED)
Mini LED
OLED (有机发光二极管)
WOLED
Micro OLED
OLED-on-Silicon
硅基 OLED
TFT-LCD
GaN LED / InGaN LED / AlGaInP LED / GaAs LED
柔性显示 (Flexible Display)
柔性技术
透明显示
全息显示
光场显示
立体显示 (3D显示)
空间显示
平板显示
微显示器 (Micro-display)
薄膜晶体管 (TFT)
非晶硅TFT (a-Si TFT)
低温多晶硅 (LTPS TFT)
氧化物TFT (IGZO TFT / Metal Oxide TFT)
有源驱动显示 (AM-Driving)
像素电路 (Pixel Circuit)
像素驱动电路
GOA电路 (Gate Driver on Array)
像素电极
Level Shifter
短沟道效应 (Short Channel Effect)
热载流子效应 (Hot Carrier Effect)
Kink Effect (扭曲效应)
液晶材料
蓝相液晶 (Blue Phase LC)
正性液晶 / 负性液晶
液晶取向
OLED材料科学
OLED发光材料 (Emitters)
磷光 OLED (Phosphorescent)
TADF (热活化延迟荧光)
QLED (量子点显示)
QLED材料科学
量子点膜 (QDEF)
量子点背光源
偏光片 (Polarizer)
偏光片技术
彩色滤光片 (Color Filters)
柔性聚酰亚胺 (Flexible PI)
Chip On PI
化学气相沉积 (CVD)
物理气相沉积 (PVD)
蒸镀技术 (Evaporation)
喷墨打印技术 (Inkjet Printing)
光刻技术 (Photolithography)
干法刻蚀 (Dry Etching)
湿法刻蚀 (Wet Etching)
制程工艺
退火 (Annealing)
准分子激光退火 (ELA)
快速热退火 (RTA)
摩擦配向 (Rubbing)
光配向 (Photo-alignment)
配向膜 (Alignment Layer)
薄膜封装 (TFE)
封装技术
OLED 封装
芯片转移 (Mass Transfer)
芯片控制
集成技术
液晶显示 LCD
背光模组
直下式背光 / 侧入式背光
Local Dimming (局部调光)
动态调光
亮度均匀性
Source Driver (源极驱动)
TCON (时序控制器)
Chip On Film (COF)
Chip On Glass (COG)
触控技术
On-cell 触控
电容触控
LVDS / mini-LVDS
V-by-One
色域 (Color Gamut)
可视角 (Viewing Angle)
光学规格
亮点缺陷
画面串扰 (Crosstalk)
像素补偿 / 灰阶补偿
不确定其他类型

"""

# 图片类型定义
IMAGE_TYPES_LIST = [
    "photo (实物摄影)", 
    "diagram (原理/结构示意图)", 
    "chart (数据图表)", 
    "scan (显微镜/扫描图)", 
    "screenshot (屏幕截图)", 
    "table (表格)", 
    "measurement (热力图/仿真图)"
]

# ==========================================
# 2. 辅助工具函数
# ==========================================

def parse_taxonomy(csv_text="/mnt/storage/dataset/PPVL_reuslts_CN/RAG-Anything/taxonomy/test.csv"):
    """解析 CSV 为纯文本列表，供 Prompt 使用"""
    df = pd.read_csv(io.StringIO(csv_text.strip()))
    df.columns = [c.strip() for c in df.columns]
    # 格式化为: "L1 > L2 > L3" 供模型理解层级
    tags = []
    titles = "名词细项"
    for _, row in df.iterrows():
        tags.append(f"{row['名词细项']}")
    return tags
def filter_str(str):
    try:
        pattern = r"^(figure|fig|图)\s?[.-]?\d+([.-]\d+)?\s*"
        cleaned_str = re.sub(pattern, "", str, flags=re.IGNORECASE)
    except:
        cleaned_str = str
    return cleaned_str
def encode_image(image_path):
    """将本地图片转换为 Base64 编码"""
    try:
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')
    except FileNotFoundError:
        return None
def parse_json(text):
    import re  
    # parse json format generated by gemeini3
    try:
        # 使用正则表达式提取 JSON 对象
        json_str = re.search(r'\{.*\}', text, re.DOTALL).group(0)
        return json.loads(json_str)
    except Exception as e:
        print(f"JSON 解析错误: {e}")
        return {}
    
    
# ==========================================
# 3. 核心 Prompt 设计
# =============
# =============================
def build_system_question_answer_prompt(question,caption = None):
    if caption is None:
        prompt = f"""
        ### 任务目标
        根据用户提供的【图片】和 【问题】，准确回答用户的问题。

        ### 用户问题
        {question}

        ### 约束条件
        - 回答必须基于图片和文本内容。
        - 如果信息不足以回答问题，请说明原因而不是猜测。
        - 回答应简洁明了，避免冗长。

        回答: 
        """
    else:
        prompt = f"""
        ### 任务目标
        根据用户提供的【图片】和 【文本上下文】以及【问题】，准确回答用户的问题。

        ### 文本上下文
        {caption}

        ### 用户问题
        {question}

        ### 约束条件
        - 回答必须基于图片和文本内容。
        - 如果信息不足以回答问题，请说明原因而不是猜测。
        - 回答应简洁明了，避免冗长。

        回答: 
        """
    return prompt
    
    
   
# ==========================================
# 4. 异步处理流水线
# ==========================================

class AsyncLabelingPipeline:
    def __init__(self, api_key="d075fa90-7412-4208-9776-188332b1f2f9"):
        # self.client = AsyncOpenAI(base_url="https://ark.cn-beijing.volces.com/api/v3",
        #                           api_key="d075fa90-7412-4208-9776-188332b1f2f9")
        google_api_key = "AIzaSyCjhCgDEZ05AGFkRWSGRRPCOWULbvvjOlw"
        self.client = genai.Client(api_key=google_api_key).aio
                                  
      
   
        self.semaphore = asyncio.Semaphore(CONCURRENCY_LIMIT) # 限制并发数

    async def process_single_item(self, item: Dict[str, Any]):
        """
        处理单条数据：Image + Context -> Classification
        item: {'id': 1, 'image_path': '...', 'context': '...'}

        # processing single data and return data tag in json format
        """
        caption = item.get('caption_expanded', 'No text provided.')
        question = item["refined_question"]
        prompt1 = build_system_question_answer_prompt(
            question=question,
            caption=caption
        )
        prompt2 = build_system_question_answer_prompt(
            question=question,
            caption=None
        )
        async with self.semaphore: # 获取信号量
            try:
                
                result_text = await self.client.models.generate_content(
                            model = "gemini-3-flash-preview",
                            contents= [
                                prompt1] + [
                                await self.client.files.upload(file=item["image_path"]),
                                types.Part.from_bytes(
                                    data = open(item["image_path"], "rb").read(),
                                    mime_type="image/jpeg",
                                )
                            ]
                            )
                
                AnswerWithCaption = result_text.text
                result_text = await self.client.models.generate_content(
                    model = "gemini-3-flash-preview",
                    contents= [
                        prompt2] + [
                        await self.client.files.upload(file=item["image_path"]),
                        types.Part.from_bytes(
                            data = open(item["image_path"], "rb").read(),
                            mime_type="image/jpeg", 
                        )
                    ]
                    )
                
                AnswerWithoutCaption = result_text.text
                
                result_json = {}
                # 合并原始 ID 以便追踪
                result_json['id'] = item['id']
                result_json["images"] = item["image_path"]
                result_json['caption'] = caption
                result_json['question'] = question
                result_json['AnswerWithCaption'] = AnswerWithCaption
                result_json['AnswerWithoutCaption'] = AnswerWithoutCaption
                result_json["answer"] = item["refined_answer"]
                
                
                print(f"✅ [ID: {item['id']}] Processed: {result_json['question']}")
                return result_json
            except genai.errors.ServerError as e:
                # if it is 503 error, we can retry
                
                if e.code == 503:
                    print(f"⚠️ [ID: {item['id']}] Server busy, retrying...")
                    # sleep for 10 s
                    await asyncio.sleep(10)
                    return await self.process_single_item(item)
                else:
                    raise e
            
            
            
            except Exception as e:
                raise e
                print(f"❌ [ID: {item['id']}] Error: {str(e)}")
                return {
                    "id": item['id'], 
                    "error": str(e),
                    "l3_tag": "ERROR",
                    "image_type": "ERROR"
                }

    async def run_batch(self, dataset: List[Dict],use_hint = True):
        """
        两阶段流水线：
        1. Classify (分类)
        2. Generate QA (生成问答)
        """
        
        # 第一步任务列表
        
        if not use_hint:
            tasks = [self.process_single_item(item) for item in dataset]
            qa_tasks = await asyncio.gather(*tasks)
            
            qa_tasks = pd.DataFrame(qa_tasks)
            
            return qa_tasks# ,final_results

async def main():


    USE_HINT=False
   
    data = pd.read_json("/home/maxzhang/datapipeline/temp_images/vqa.json")
    data["id"] = range(1, len(data) + 1)
    # data["figure_title"] = data["figure_title"].apply(lambda x: filter_str(x))
    data["image_path"] = data["image_path"].apply(lambda x: "./temp_images/"+x.split("/")[-1])
    print(data.head())
    dataset = data
    # with open("/mnt/storage/dataset/PPVL_reuslts_CN/json_file/filter_qiuping_all_deduplicated_v0.3.1.json","r") as f:
    #     dataset = json.load(f)[:20]
    dataset = dataset.sample(n=min(70,len(dataset))).to_dict('records')
    # for i in range(len(dataset)):
    #     dataset[i]["id"] = i+1
    # # 为了演示，创建一个假的本地图片文件，防止代码报错
    # os.makedirs("test_images", exist_ok=True)


    # 2. 初始化 Pipeline
    pipeline = AsyncLabelingPipeline(api_key=API_KEY)
    
    print(f"🚀 开始处理 {len(dataset)} 条数据 (并发数: {CONCURRENCY_LIMIT})...")
    
    # 3. 运行
    results = await pipeline.run_batch(dataset,use_hint=USE_HINT)
    
    # 4. 保存结果
    output_df = pd.DataFrame(results)
    print("\n🎉 处理完成！结果预览：")

    # output_df = output_df[["image_path","figure_title","related_text_strong","generated_question","generated_answer","pass", "score","filter_reason"]]
    output_df.to_csv("question_answer_results.csv", index=False)
    print(output_df.head())
    # 保存为 JSONL 或 CSV 供下一步使用
    # with open("keyword_results34.json","w") as f:
    #     json.dump(results,f,ensure_ascii=False)
    path = "/home/maxzhang/datapipeline/temp_images/question_answer_compare.json"
    output_df.to_json(path, orient="records", force_ascii=False)
    #output_df.to_json("/home/maxzhang/datapipeline/temp_images/keyword_results_added_vqa_with_background.json", orient="records", force_ascii=False)
    # update original table with the column keyword
    
    print(f"💾 结果已保存到 {path}")
    
if __name__ == "__main__":
    # Windows/Jupyter 环境可能需要 nest_asyncio
    # import nest_asyncio
    # nest_asyncio.apply()
    
    asyncio.run(main())