import asyncio
import aiohttp
import pandas as pd
from aiohttp import ClientSession
from tqdm.asyncio import tqdm
from openai import AsyncOpenAI
from typing import List, Dict, Any
from hintfactory import HintFactory
from google import genai
from google.genai import types
import json
import openai
from openai import AsyncOpenAI
def parse_json(text):
    import re  
    # parse json format generated by gemeini3
    try:
        # 使用正则表达式提取 JSON 对象
        json_str = re.search(r'\{.*\}', text, re.DOTALL).group(0)
        return json.loads(json_str)
    except Exception as e:
        print(f"JSON 解析错误: {e}")
        return {}
def encode_image_to_base64(image_path: str) -> str:
    import base64
    with open(image_path, "rb") as image_file:
        encoded_string = base64.b64encode(image_file.read()).decode("utf-8")
    image_type = image_path.split('.')[-1]
    return f"data:image/{image_type};base64,{encoded_string}"
# Google API 请求函数
def build_prompt(question: str,answer: str, context: str) -> str:
    prompt = f"""▶ ROLE
            你是一个逻辑严谨的推理专家，能基于标准答案反向还原自然连贯的思考路径。

            ▶ TASK
            我会提供【问题】和对应的【答案】。你的任务是基于这个答案，反向还原出自然的思考路径，模拟人类解决该问题时的推理过程。

            ▶ CONSTRAINTS
            1. 推理过程必须逻辑闭环，每一步推导都要和下一步紧密衔接，有理有据。
            2. 严格以【答案】为终点，所有思考步骤都要服务于最终得出该答案。
            3. 必须使用 “首先、其次、然后、因此” 等连接词串联步骤，全程禁止使用任何标题、分节符或类似 “XX 部分” 的表述。
            4. 语言风格要自然流畅，避免生硬的结构化分点，让思考路径看起来是 “一气呵成” 的推导，而非刻意划分的模块。

            ▶ INPUT
            【问题】：
            {context}
            {question}

            【答案】：
            {answer}

            ▶ OUTPUT
            以 以下格式输出：
            {{
                "thought_process": "你的自然思考路径内容"
            }}
            
            请生成自然的思考路径：
            """
    return prompt
def build_question_distil(question: str,answer:str, context: str) -> str:  
    prompt = f"""
            ▶ ROLE
             图片:
             <image>
            
            【问题】：
            {context}
            {question}

            【答案】：
             """
    return prompt
async def check_question_quality(client, question: str,reasoning_process:str, answer: str, standard_answer: str, original_text: str, mode: int = 1) -> dict:
    """
    检查问题质量或从多个维度对问题进行评分。

    Args:
        client: Google Gemini3 API 客户端。
        question (str): 要检查的问题。
        answer (str): 问题对应的回答。
        standard_answer (str): 标准答案。
        original_text (str): 生成问题的原文。
        mode (int): 检查模式，1 为质量检查，2 为多维度评分。

    Returns:
        dict: 包含检查结果或评分的字典。
    """
    try:
        # 构建不同模式下的 prompt
        if mode == 1:
            prompt = f"""
            ▶ ROLE
            你是一个问题质量检查专家，能够判断问题和答案是否符合质量要求。

            ▶ TASK
            我会提供【问题】、【回答】、【标准答案】和【原文】。你的任务是检查问题和答案是否质量合格。

            ▶ CONSTRAINTS
            1. 质量合格的标准包括：问题是否清晰、回答是否准确、是否与标准答案一致。
            2. 如果质量不合格，请指出具体问题。
            3. 思考过程和回答是否和原文内容冲突，如果冲突请判断为不合格。

            ▶ INPUT
            【问题】：
            {question}
             
            【解答过程】：
            {reasoning_process}
            【回答】：
            {answer}

            【标准答案】：
            {standard_answer}

            【原文】：
            {original_text}

            ▶ OUTPUT
            请判断问题和答案是否质量合格并以下格式输出：
            {{
                "is_qualified": true/false,
                "issues": ["issue1", "issue2", ...] // 如果不合格，列出具体问题
            }}
            
            这个问题和答案的质量检查结果是:
            """
        elif mode == 2:
            prompt = f"""
            ▶ ROLE
            你是一个问题评分专家，能够从多个维度对问题进行评分。

            ▶ TASK
            我会提供【问题】、【回答】、【标准答案】和【原文】。你的任务是从以下维度对问题进行评分：
            - 相关性：问题是否与原文内容相关。
            - 准确性：回答是否与标准答案一致。
            - 专业性：问题和回答是否符合专业领域的要求。
            - 全面性：问题是否覆盖了原文的核心内容。

            ▶ CONSTRAINTS
            1. 每个维度的评分范围为 0-10 分。
            2. 最后给出一个综合评分（0-10 分）。

            ▶ INPUT
            【问题】：
            {question}

            【回答】：
            {answer}

            【标准答案】：
            {standard_answer}

            【原文】：
            {original_text}

            ▶ OUTPUT
            请从相关性、准确性、专业性、全面性四个维度评分，并给出综合评分
            请按以下格式输出：
            {{
                "relevance": score,
                "accuracy": score,
                "professionalism": score,
                "comprehensiveness": score,
                "overall_score": score
            }}
            这个问题的评分结果是:
            """

        # 调用 Gemini3 API
        result_text = await client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=[prompt]
        )

        # 解析结果
        
        return result_text

    except Exception as e:
        print(f"检查问题质量时发生错误: {e}")
        return {"error": str(e)}
    
async def call_model_api(client, question: str,answer:str, image_path: str,context: str,use_openai:bool) -> dict:
    try:
        if not use_openai:
            contents = [
                build_prompt(question, answer, context),
                await client.files.upload(file=image_path),
                types.Part.from_bytes(
                    data = open(image_path, "rb").read(),
                    mime_type="image/jpeg",
                )
                ]
            
            result_text = await client.models.generate_content(
                        model = "gemini-3-flash-preview",
                        contents= contents
                        )
            print(result_text.text)
            result_json = parse_json(result_text.text)
            think_process = result_json.get("thought_process", "")
            response_answer = answer
        else:
            base_url="https://ark.cn-beijing.volces.com/api/v3"
            api_key="d075fa90-7412-4208-9776-188332b1f2f9"
            model = "ep-20251028151816-lv47m" 
            think_process,answer = await call_openAI_api(base_url,model,api_key,question,answer, image_path,context)
            result_json={
                "doubao_thought_process": think_process,
                "doubao_distilled_answer": answer
            }
        if not think_process:
            return ""
        check_results = await check_question_quality(client, question,think_process, answer, answer, context, mode=1)
        check_results = parse_json(check_results.text)
        return {
            **check_results,
            **result_json
        }
        
    except Exception as e:
        
        raise e
    
async def call_openAI_api(base_url,model,api_key,question: str,answer:str, image_path: str,context: str) -> dict:

    client = AsyncOpenAI(api_key=api_key, base_url=base_url)
    
    messages = [
            {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": build_question_distil(question, answer, context)
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": encode_image_to_base64(image_path)
                    }   }
            ]}
        ]
    response = await client.chat.completions.create(
        model=model,
        messages=messages,
        max_tokens=8192)
    answer = response.choices[0].message.content
    reasoning = response.choices[0].message.reasoning_content
    
    
    return reasoning,answer
    
def filter_str(str):
    import re
    try:
        pattern = r"^(figure|fig|图)\s?[.-]?\d+([.-]\d+)?\s*"
        cleaned_str = re.sub(pattern, "", str, flags=re.IGNORECASE)
    except:
        cleaned_str = str
    return cleaned_str

# 去除编号
# 并发处理函数
async def process_data(lock,client,data,use_openai):
    async with lock:
        tasks = []
        for _, row in data.iterrows():
            question = row["generated_question"]
            answer = row["generated_answer"]
            question = filter_str(question)
            
            assert answer is not None, f"Answer is None for question: {question}"
            image_path = row["image_path"]
           
            figure_title = filter_str(row["figure_title"])
            tasks.append(call_model_api(client, question,answer, image_path,figure_title,use_openai))
        results = await tqdm.gather(*tasks, desc="Processing", ncols=100)
        # convert results to list of dict and merge then with original data
        results_data = pd.DataFrame(results)
        # 将 results_data 合并到 data 中
        return results

# 主函数
def main(client,input_csv: str, output_csv: str):
    # 读取 CSV 文件
    from asyncio import Semaphore
    lock = Semaphore(16)  # 限制并发请求数为 5
    data = pd.read_csv(input_csv)
    data["image_path"] = data["image_path"].apply(lambda x: "./"+x)
    # 检查必要的列
    if "generated_question" not in data.columns or "image_path" not in data.columns:
        raise ValueError("Input CSV must contain 'generated_question' and 'image_path' columns.")
    
    # 运行异步任务
    results = asyncio.run(process_data(lock,client,data,use_openai=False))
    
    # 将结果添加到 DataFrame
    data["answer_results"] = results
    
    
    # 保存到新的 CSV 文件
    data.to_csv(output_csv, index=False)
    print(f"✅ 数据已保存到 {output_csv}")

# 调用主函数
if __name__ == "__main__":
    input_csv = "/Users/Shared/taxonomy_pipeline/FlashGeneratedVqa.csv"  # 替换为你的输入 CSV 文件路径
    output_csv = "gemini3_distilled.csv"  # 替换为你的输出 CSV 文件路径
    google_api_key = "AIzaSyCjhCgDEZ05AGFkRWSGRRPCOWULbvvjOlw"
    client = genai.Client(api_key=google_api_key).aio
    main(client,input_csv, output_csv)
